<?php

namespace AppBundle\Repository;

/**
 * HoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoteRepository extends \Doctrine\ORM\EntityRepository
{
}
