<?php

namespace AppBundle\Repository;

/**
 * InformationPersonnelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationPersonnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
