<?php

namespace AppBundle\Repository;

/**
 * IntegrateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrateurRepository extends \Doctrine\ORM\EntityRepository
{
}
