<?php

namespace AppBundle\Repository;

/**
 * PlateformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateformeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRole($role)
    {
        return $this->getEntityManager()
            ->createQuery('
            SELECT p FROM AppBundle:Plateforme p WHERE ');
    }
}
